name: "CI"

on:
  push:
    branches:
      - main

jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ matrix.platform }}-${{ matrix.args }}
          workspaces: 'src-tauri -> target'

      - name: install packages
        if: matrix.platform == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install javascriptcoregtk-4.1 libsoup-3.0 webkit2gtk-4.1 librsvg2-dev -y

      - name: install frontend dependencies
        run: npm ci
      
      - name: test
        run: npm run test

      - name: lint
        run: npm run lint

      - name: build
        run: npm run tauri build -- --verbose
      